### ISSUE TITLE
Update selector to use type = text

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-forms#1]
We are currently styling all inputs as textfields. The following should be changed after 1.0 because there are some inputs that are not textfields like button, submit, date, etc.

``` CSS
input,
textarea {
...
```

Should be

``` CSS
input[type="text"],
textarea {
...
```

**Comment by Scotchester** [comment]
For future-proofing, should probably apply it to all that behave the same as a regular text field, as well. E.g., email, phone, url, etc.

http://html5doctor.com/html5-forms-input-types/

**Comment by himedlooff** [comment]
Word.

**Comment by iuloshi** [comment]
Hey guys,

We're using radio buttons and checkboxes in the Design Manual ([see comp](https://github.com/cfpb/design-manual/issues/145)), but right now all inputs are getting styled as text inputs. Is there a hacky override I could use temporarily or do you think you'd be able to push a quick update to CF?

http://iuloshi.github.io/design-manual/ui-toolkit/form-fields.html

![screen shot 2014-04-18 at 6 56 20 pm](https://cloud.githubusercontent.com/assets/1676307/2746644/c0455ace-c74c-11e3-903c-606d9ee0d792.png)

As always, thanks for your help!! :cat:

**Comment by contolini** [comment]
We just bumped into this bug with range sliders on OAH.

**Comment by himedlooff** [comment]
Yeah I can fix the styling to focus only on text inputs and text areas.

**Comment by himedlooff** [comment]
Ok, design-manual and oah should update to version 0.5.0 of cf-forms in order to take advantage of the less aggressive input styling.

**Comment by iuloshi** [comment]
Do I do this in...Bower? :smiley:

**Comment by himedlooff** [comment]
Try `bower update cf-forms`.

**Comment by iuloshi** [comment]
Sweet! Thanks @himedlooff!! Now I just need to style these suckers.

![screen shot 2014-04-21 at 5 35 46 pm](https://cloud.githubusercontent.com/assets/1676307/2759218/0b799e54-c99d-11e3-98c3-2172e4e3dd92.png)

**Comment by himedlooff** [comment]
I didn't think there was official guidance yet on these. Are there?

**Comment by iuloshi** [comment]
Will check with the other PQ&S folks.

Did you guys also explore custom form elements for checkboxes, radio buttons, and/or dropdown menus? If so, are those going to get pulled into CF? If not, no worries--I think we'll just include the default browser form elements in the Design Manual and perhaps set some styling guidelines for labels, etc.

**Comment by himedlooff** [comment]
We explored custom checkboxes and we're lined up to style them within the next few weeks.

**Comment by iuloshi** [comment]
Sweet! Will keep a lookout to include in the Design Manual.
