### ISSUE TITLE
Super input with button text appears too large?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-forms#28]
In the last example on http://cfpb.github.io/cf-forms/docs/, the text spills outside the bounds of the button:

![screen shot 2015-01-27 at 5 42 39 pm](https://cloud.githubusercontent.com/assets/704760/5928816/005cb574-a64c-11e4-905d-6e7a19d17d54.png)

**Comment by himedlooff** [comment]
Yeah we could make some tweaks here. Or maybe replace it with the version you were playing around with.

**Comment by anselmbradford** [comment]
:+1:
