### ISSUE TITLE
Text input fields

### ISSUE THREAD

**Issue by cfarm** [cfpb/cf-forms#36]
@sonnakim Tracking development of the form fields here.

Wireframe:
![screen shot 2015-09-15 at 5 58 00 pm](https://cloud.githubusercontent.com/assets/702526/9891291/5b108be8-5bd3-11e5-8d9a-393b5dc218bb.png)

**Comment by cfarm** [comment]
@sonnakim I noticed in your wireframe you have "Disabled placeholder text" in the example field. None of the others have the field type in front, like "Error placeholder text," so I'm thinking we keep it consistent and just "Placeholder text" like the others.

**Comment by cfarm** [comment]
@Scotchester can you add @sonnakim and @stephanieosan to this repo's users so I can easily notify them? Thanks.

**Comment by sonnakim** [comment]
@cfarm Good idea. We can use "Placeholder text"  for the multiline text input field as well.

**Comment by cfarm** [comment]
@Scotchester @jimmynotjim @KimberlyMunoz I noticed that some default form styles (input type text, etc) are in cf-core:

https://github.com/cfpb/cf-core/blob/gh-pages/src/cf-base.less#L635

Do we want to keep them there?

**Comment by Scotchester** [comment]
My preferred rule of thumb is that if you're just modifying the default styling of a standard HTML element (e.g., basic `input` or `label` styling), it should be done in cf-core. More advanced patterns, groups of things, or anything that would require JS should happen in cf-forms.

**Comment by cfarm** [comment]
:+1: sounds good.
